# Generated by Django 4.1.3 on 2023-02-20 02:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_news_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
