# Generated by Django 4.1.3 on 2023-01-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainbow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='Testimony',
            new_name='testimony',
        ),
    ]
