# Generated by Django 4.1.3 on 2023-01-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainbow', '0003_rename_prayer_prayer_prayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name_plural': 'Testimonies'},
        ),
    ]
