# Generated by Django 4.1.3 on 2023-01-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('ebook', models.FileField(upload_to='ebooks')),
            ],
            options={
                'verbose_name_plural': 'Ebooks',
            },
        ),
    ]
