# Generated by Django 4.1.3 on 2023-04-26 12:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('ebook', models.FileField(upload_to='ebooks')),
            ],
            options={
                'verbose_name_plural': 'Ebooks',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('info', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='events_images')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='SabbathArchiveVideoLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'SabbathArchiveVideoLinks',
            },
        ),
        migrations.CreateModel(
            name='StudyGuides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('guide', models.FileField(upload_to='guides')),
            ],
            options={
                'verbose_name_plural': 'StudyGuides',
            },
        ),
        migrations.CreateModel(
            name='StudyToShowVideoLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'StudyToShowVideoLinks',
            },
        ),
        migrations.CreateModel(
            name='Tracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('tract', models.FileField(upload_to='tracts')),
            ],
            options={
                'verbose_name_plural': 'Tracts',
            },
        ),
    ]
