# Generated by Django 4.1.3 on 2023-03-21 08:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_links_date_filed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyVideoLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'StudyVideoLinks',
            },
        ),
    ]
