# Generated by Django 4.1.3 on 2023-03-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_studyguides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('tract', models.FileField(upload_to='tracts')),
            ],
            options={
                'verbose_name_plural': 'Tracts',
            },
        ),
    ]
